name: Docker Image CI/CD for Staging

on:
  push:
    branches: ["main"]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Store variables
        id: get-store
        run: |
          echo version=$(jq -r '.version' package.json) >> $GITHUB_OUTPUT
          echo branch=${GITHUB_REF##*/} >> $GITHUB_OUTPUT

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ env.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ env.DOCKER_ORG }}/bun-expense-app:${GITHUB_REF##*/}-${{ steps.get-store.outputs.version }}

      - name: Docker Push
        run: docker push ${{ env.DOCKER_ORG }}/bun-expense-app:${GITHUB_REF##*/}-${{ steps.get-store.outputs.version }}
