name: Docker Build and Push Multi-Arch (Unified)

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Current Version
        run: echo current version $(node -p "require('./package.json').version")

      - name: Save Version
        run: echo "PACKAGE_VERSION=${GITHUB_REF##*/}-$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Current Version From Env
        run: echo "Package version is ${{ env.PACKAGE_VERSION }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: "jtievista/nimbus"
          platforms: linux/amd64,linux/arm64

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: "${{ vars.DOCKER_USER }}/docker-build-cloud-demo:latest"
          # For pull requests, export results to the build cache.
          # Otherwise, push to a registry.
          outputs: ${{ github.event_name == 'pull_request' && 'type=cacheonly' || 'type=registry' }}

      - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          username: Harmony Dashboard Production
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          username: Harmony Dashboard Production
          severity: error
          details: Test Failed!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Test Cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: cancelled()
        with:
          username: Harmony Dashboard Production
          severity: warn
          details: Test Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
